CREATE PROCEDURE SP_ADD_USER (
    P_USERNAME DM_USERNAME
)
AS
BEGIN
    INSERT INTO USERS (ID, USERNAME) VALUES (GEN_ID(GEN_USERS_ID, 1), P_USERNAME);
END;

CREATE PROCEDURE SP_LIST_USERS
AS
BEGIN
    FOR SELECT ID, USERNAME, CREATED_AT FROM USERS INTO :ID, :USERNAME, :CREATED_AT
    DO
        SUSPEND;
END;