-- Tabela użytkowników
CREATE TABLE USERS (
    ID DM_ID PRIMARY KEY,
    USERNAME DM_USERNAME,
    CREATED_AT DM_DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabela ról
CREATE TABLE ROLES (
    ID DM_ID PRIMARY KEY,
    ROLE_NAME VARCHAR(50) NOT NULL
);

-- Tabela przypisania użytkowników do ról
CREATE TABLE USER_ROLES (
    USER_ID DM_ID NOT NULL,
    ROLE_ID DM_ID NOT NULL,
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);